name: JavaScript Action
description: Greet someone from the javascript custom action

inputs:
  who-to-greet: # id of input
    description: Who to greet
    required: true
    default: World

runs:
  using: node20
  main: dist/index.js
