name: This is a callable workflow
on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
        default: 'World peter'
    outputs:
      firstword:
        description: "The first output string"
        value: "Hello,This is the output from the callable workflow. my name is ikechukwu"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{inputs.name}}! this is the callable workflow"
    
      
    