name: this is a calling workflow
on:
  push:
    branches:
      - master
jobs:
  call_workflow:
    uses: ./.github/workflows/callable_workflow.yml
  another_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World! this is the calling workflow"