name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo "This is a GitHub Actions demo workflow."
      - run: echo "You can customize this workflow to suit your needs."
  build2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is another job in the same workflow."
      - run: echo "You can have multiple jobs running in parallel or sequentially."
  build3:
    needs: [build, build2 ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is yet another job in the same workflow. on build 3 job"
      - run: echo "GitHub Actions allows you to automate your software development workflows."